import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import Post from './Post';
import QueryWrapper from './QueryWrapper'
import Banner from '@/components/Banner'
import Header from '@/components/Header'

async function allPosts() {
  const res = await axios(`${process.env.BASE_URL}/api/getPosts`);

  return res.data;
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryWrapper>
        <main>
          <Header />
          <Banner />
          <div>
            <h1 className="text-3xl font-bold underline">Hello world!</h1>
          </div>
        </main>
      </QueryWrapper>
    </>
  );
}
